### ISSUE TITLE
[Small screen] - Navigation should match the old design

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/developer.ubuntu.com#28]
Same as the current developer website.
- Size& position of the top nav; hamburger icon; search icon 
- Menu behaviour & design
- Font size; hover states; select state

**Comment by joanasa89** [comment]
Same as the current developer website.
- Size& position of the top nav; hamburger icon; search icon 
- Menu behaviour & design
- Font size; hover states; select state

**Comment by grahambancroft** [comment]
Part fixed on demo - http://developer.ubuntu.com-add-template-code.demo.haus

Search is being addressed with issue 21

**Comment by joanasa89** [comment]
@grahambancroft 
- Height of top nav should match dev website
- Hamburger menu size should match the size of dev website
- Search icon still missing
- Core doesn't have child content
- Hide the other navigation

**Comment by deadlight** [comment]
@grahambancroft is this still valid?
